### ISSUE TITLE
tweets command not found after PR

### ISSUE THREAD

**Issue by hajderr** [Heaplevel/discord-heaplevelbot#2]
in Discord typing $tweets <search term> causes 

Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "tweets" is not found

**Comment by NoirPi** [comment]
That's not a bug cause the tweets function is not loaded due to the module is commented in the main.py

Uncomment it and it will work.

Reason why all tweet related functions were moved in one file is that there is still no example for file structure of credentials and without that the bot won't start
